# Generated by Django 5.2 on 2025-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_icon', models.CharField(max_length=50)),
                ('about_title', models.CharField(max_length=50)),
                ('about_des', models.TextField()),
            ],
        ),
    ]
